version: "3"

services:
  pgdb:
    image: "postgres:alpine"
    container_name: "$DB_CONTAINER"
    env_file:
      - .env
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PWD
    ports:
      - "$DB_PORT:5432"
    volumes:
      - $DB_VOLUME_DATA:/var/lib/postgresql/data
